/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AnalyzedHistory } from "./AnalyzedHistory";
import { AnalyzedHistoryCountArgs } from "./AnalyzedHistoryCountArgs";
import { AnalyzedHistoryFindManyArgs } from "./AnalyzedHistoryFindManyArgs";
import { AnalyzedHistoryFindUniqueArgs } from "./AnalyzedHistoryFindUniqueArgs";
import { DeleteAnalyzedHistoryArgs } from "./DeleteAnalyzedHistoryArgs";
import { AnalyzedHistoryService } from "../analyzedHistory.service";
@graphql.Resolver(() => AnalyzedHistory)
export class AnalyzedHistoryResolverBase {
  constructor(protected readonly service: AnalyzedHistoryService) {}

  async _analyzedHistoriesMeta(
    @graphql.Args() args: AnalyzedHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AnalyzedHistory])
  async analyzedHistories(
    @graphql.Args() args: AnalyzedHistoryFindManyArgs
  ): Promise<AnalyzedHistory[]> {
    return this.service.analyzedHistories(args);
  }

  @graphql.Query(() => AnalyzedHistory, { nullable: true })
  async analyzedHistory(
    @graphql.Args() args: AnalyzedHistoryFindUniqueArgs
  ): Promise<AnalyzedHistory | null> {
    const result = await this.service.analyzedHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyzedHistory)
  async deleteAnalyzedHistory(
    @graphql.Args() args: DeleteAnalyzedHistoryArgs
  ): Promise<AnalyzedHistory | null> {
    try {
      return await this.service.deleteAnalyzedHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
